### PR TITLE
:pencil: Add Nix installation to README

### PR DESCRIPTION
**Pull request by NeQuissimus**

### CODE REVIEW

**Review by mislav — APPROVED** [review]
Thanks!

**Review by codedfile — COMMENTED** [review]
README.md

**Comment by codedfile** [comment]
> README.md

**Review by codedfile — APPROVED** [review]
0b50b8f292698046a809a114ffdb8a14ff2fb131

**Comment by KHOENIX** [comment]
Leave a comment

**Comment by KHOENIX** [comment]
Leave a comment

**Pull request merged**
