### PR TITLE
Add pr push command

### PR DESCRIPTION
**Pull request by jridgewell**
Sometimes contributors need help with the PRs.

So, you checkout with `hub pr checkout 123`, and make some changes (possibly rebasing). But then, where the hell do you push the changes to?

GitHub’s [official docs](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/) (besides being impossible to find) say to clone (!!!) the fork to push changes to the branch. If you’re advanced, maybe you make a remote, then push to it using a `local-branch:remote-branch` refspec. It’s way too hard.

So, enter `hub pr push 123`. It pushes the current branch to the PR’s remote branch without adding a remote or cloning. Or, you can `hub pr push 123 local-branch` if you want to push the `local-branch` branch in place of the current. You can even `--force` push, or `--set-upstream` while you do it.

### CODE REVIEW

**Comment by timofonic** [comment]
@jridgewell This looks really nice! Thanks a lot! Why nobody at GitHub Team replied yet? :/

**Comment by jridgewell** [comment]
Bump. Anything I can do to get this reviewed?

**Comment by jridgewell** [comment]
Rebased this so it merges clean. Any chance I can get a review?

**Comment by mislav** [comment]
@jridgewell Thank you for your idea! Somehow I missed this, sorry.

What if `git push` simply worked instead? Here is [my idea how to achieve this](https://github.com/github/hub/issues/1495#issuecomment-310065377).

**Comment by jridgewell** [comment]
Going though #1495, it seems like we can create a new `branch.<name>.pushBranch` configuration to define what branch to push the local branch, and to pair with git's already supported `branch.<name>.pushRemote` which defines which remote to push to.

This would mirror `branch.<name>.remote` and `branch.<name>.merge` for the pulling side of things.

Using that, we have three cases in the current checkout (and pr checkout) flows:

1. same repo
   - Checks out the branch using normal commands
   - If a local branch name is different than remote branch name, sets `merge` and `pushBranch`
2. already-added remote
   - Checks out the branch using normal commands
   - Sets `remote` and `pushRemote` to the remote's shortname
   - If a local branch name is different than remote branch name, sets `merge` and `pushBranch`
3. foreign remote
   - Checks out the branch using normal commands
   - Sets `remote` and `pushRemote` to `git@github.com:PRAUTHOR/REPO.git` (or https)
     - This could also use `remote` set to the default remote, paired with a `heads/pull/NUM/head` `merge`, but then you'd have to fetch that after any push. Seems more convenient to just define them as the same value.
   - If a local branch name is different than remote branch name, sets `merge` and `pushBranch`

This'll also affect the `pull-request`, `browse`, and `compare` commands, since we are defining a way configure the push target of any branch.

**Comment by weitzman** [comment]
This PR is green and adds significant test coverage. Anything else needed?

**Comment by mislav** [comment]
After #1764, this should no longer be necessary:

```
hub pr checkout 123
// ... make changes & commit ...
git push
```

should just work.

**Pull request closed without merging**
