### PR TITLE
Fix <USER> in usage string

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by mislav** [comment]
Good catch! Please sign the CLA (see the checks section of this PR) so I can merge this. And don't worry about the Travis failure; it looks like it's due to something other than your change.

**Comment by strk** [comment]
haven't found an easy way, feel free to take the suggestion and fix it in your own way

**Comment by mislav** [comment]
@strk It's very easy! Just click here:

hub 2017-01-09 17-16-57

**Comment by strk** [comment]
done

**Comment by mislav** [comment]
Thank you! 🏆

**Pull request merged**
