### PR TITLE
Improve label contrast ratios

### LINKED ISSUE #1960: Label contrast in "hub pr list" could use some improvement
**hub version 2.3.0**

The labels shown in `hub pr list` output could use some improvement for readability. Here's an example from one of my repos:

image

And another screenshot where I've highlighted the second PR in my console (to show the text that's there):

image

FWIW here are the label configs for those shown in the screenshot: 

```json
{
  "affects/v4": "5319e7",
  "effort/medium": "fef2c0",
  "impact/high": "eb6420"
}
```

I understand that GitHub automatically determines the text colour for you based on the background colour you provide. I'm not sure how `hub` renders these hex codes into terminal colours, but I think there's some improvement to be made with the same kind of logic here - the `affects/v4` label is kind of readable, but the other two aren't really (`effort/medium` is almost invisible).

I'm happy help with this if someone could point me at the part of the code to start looking at =)

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #1960.
Depends on and includes #1979.

This PR improves the contrast ratios of displayed label text by using a more sophisticated algorithm for picking foreground colors to go with the background issue colors.

I'm not sure I got the color candidate calculation right, because I'm not sure I understood the use of the terms "lightness" and "brightness" [in this comment](https://github.com/github/hub/issues/1960#issuecomment-443743138)

### CODE REVIEW

**Comment by apjanke** [comment]
I've modified this PR to fix the test, changing the expected formatting to use the new 3-component color codes instead of the old palettized color codes.

**Comment by apjanke** [comment]
Hmm. The Travis build is failing with this:

```
1.01s$ make test-all
script/test --coverage 89.4
main.go:9:2: cannot find package "github.com/github/hub/commands" in any of:
	/home/travis/gopath/src/github.com/apjanke/hub/vendor/github.com/github/hub/commands (vendor tree)
	/home/travis/.gimme/versions/go1.10.7.linux.amd64/src/github.com/github/hub/commands (from $GOROOT)
	/home/travis/gopath/src/github.com/github/hub/commands (from $GOPATH)
main.go:4:14: cannot find package "github.com/github/hub/coverage" in any of:
	/home/travis/gopath/src/github.com/apjanke/hub/vendor/github.com/github/hub/coverage (vendor tree)
	/home/travis/.gimme/versions/go1.10.7.linux.amd64/src/github.com/github/hub/coverage (from $GOROOT)
	/home/travis/gopath/src/github.com/github/hub/coverage (from $GOPATH)
main.go:10:2: cannot find package "github.com/github/hub/github" in any of:
	/home/travis/gopath/src/github.com/apjanke/hub/vendor/github.com/github/hub/github (vendor tree)
	/home/travis/.gimme/versions/go1.10.7.linux.amd64/src/github.com/github/hub/github (from $GOROOT)
	/home/travis/gopath/src/github.com/github/hub/github (from $GOPATH)
main.go:11:2: cannot find package "github.com/github/hub/ui" in any of:
	/home/travis/gopath/src/github.com/apjanke/hub/vendor/github.com/github/hub/ui (vendor tree)
	/home/travis/.gimme/versions/go1.10.7.linux.amd64/src/github.com/github/hub/ui (from $GOROOT)
	/home/travis/gopath/src/github.com/github/hub/ui (from $GOPATH)
make: *** [test-all] Error 1
The command "make test-all" exited with 2.
```

https://travis-ci.com/apjanke/hub/builds/96120106?utm_medium=notification&utm_source=email

Is that my fault?

**Comment by apjanke** [comment]
Can you give me an example of where the contrast looks worse in Terminal.app? I've been testing it against the silverstripe/silverstripe-admin repo that robbieaverill mentioned, and it looks better there. Here's hub 2.6.1 vs this PR for me:

hub-labels-before-after

Offhand, I guess the issue could be that the old version is considering pure black and pure white as its candidates, and they should be added to the candidate color list in this PR in addition to the colors derived from the lightening/darkening algorithm?

**Comment by mislav** [comment]
I've just pushed a simplified version. Please review.

I'm afraid I've sent you on a wild goose chase with my [initial specification for this feature](https://github.com/github/hub/issues/1960#issuecomment-443743138). Although my comment was a near-accurate reflection of our server-side logic when picking a contrasting color candidate, I have failed to pick up that we also add black `#000` and white `#fff` into the mix as potential candidates with priority, and because one of these always has a satisfying contrast, the result with always be either `#fff` or `#000`. Therefore, adding extra candidates using HSL transforms (which you've handled almost impeccably in your implementation; there were only slight bugs in the luminosity vs. brightness adjustments) would be a waste of CPU cycles. I have therefore removed the unnecessary parts of the implementation.

screen shot 2019-01-03 at 4 26 26 am

**Comment by apjanke** [comment]
Oh well, it was a fun exercise!

The new simplified version of the code looks good to me, and seems to work well when I've tested it against silverstripe-admin and a couple other repos, for both issues and prs. Looks good to me in both iTerm and Terminal.app. Colors do seem to match those displayed in the GitHub web interface in my testing too.

Looks good.

**Pull request merged**
