### PR TITLE
Enable team reviewers in `pull-request`

### LINKED ISSUE #1633: Add 'team reviewers' using -r
It is not currently possible to add team reviewers to a pull request via the `-r` switch.

### PR DESCRIPTION
**Pull request by mislav**
Fixes #1633

### CODE REVIEW

**Comment by axos88** [comment]
This should also be documented

**Comment by axos88** [comment]
Do you have any idea when the next prerelease will be available with homebrew that includes this?

**Comment by mislav** [comment]
@tedmdelacruz It's in master and not yet part of any packaged release.

**Comment by johnofcamas** [comment]
When do releases get packaged?

**Comment by jasonkarns** [comment]
Can install from master (if using macOS + homebrew) using: `brew install --HEAD hub`

**Comment by mislav** [comment]
Also, version 2.3.0 (including this feature) was released just the other day: https://github.com/github/hub/releases/tag/v2.3.0

**Comment by josh-g3** [comment]
So this is in? And is this the proper syntax?

>`hub pull-request ... -r <org_name>/<team_name>`

**Comment by mislav** [comment]
@josh-g3 Yes. Although the `<org_name>` part is ignored (you cannot request reviewers from an org different than the one the repo is in, anyway), so most of the time I just type `hub pull-request -r/<team_name>`. The slash is the only important bit to distinguish it from usernames.

**Pull request merged**
