### PR TITLE
Fix password insertion more than 15 characters on Windows

### PR DESCRIPTION
**Pull request by jingweno**
Bumping to the latest gopass. This fixes https://github.com/github/hub/issues/837.

### CODE REVIEW

**Comment by mislav** [comment]
Nice! Have you tested on Windows?

I restarted the intermittent failing build, btw

**Comment by jingweno** [comment]
@mislav Yes, I tested on Windows and it works.

**Comment by mislav** [comment]
Awesome!

I must say I'm looking at the diff of the fix and I don't understand.

**Comment by jingweno** [comment]
>  I must say I'm looking at the diff of the fix and I don't understand.

I should have put more description. [This commit](https://github.com/howeyc/gopass/commit/2c70fa70727c953c51695f800f25d6b44abb368e) fixes NUL (0 byte) returning from getch on 64 bit Windows.

**Pull request merged**
