### PR TITLE
Add hub-apr

### PR DESCRIPTION
**Pull request by ryo33**
Applying patches from PR number like `$ hub apr 33` or `$ hub apr "#33"`.

### CODE REVIEW

**Comment by mislav** [comment]
Hi thanks for the excellent pull request. However, is this basically equivalent to `hub apply <pullrequest-url>`?

**Comment by ryo33** [comment]
`hub apr <pullrequest-number>` will be transformed to `hub am -3 <pullrequest-url>` for now.
Please see https://github.com/ryo33/hub/blob/hub-apr/commands/apply_test.go#L11-L16 for reference.

**Comment by mislav** [comment]
So this is just a shortcut for `am -3 <pullrequest-url>`? I feel we need something like this, although I'm not a fan of a new command called `apr`.

I was thinking about making a new command called `hub pr` or something that will handle everything PR related: from opening them, browsing them, checking them out as branches, to merging.

**Comment by ryo33** [comment]
Yes, it's just a shortcut.
So the shortcut should be `hub pr --am -3 <pullrequest-number>`?

**Pull request closed without merging**
