### PR TITLE
Updated README.md with Ubuntu Snap install instructions

### PR DESCRIPTION
**Pull request by sethwebster**
Adds a section for installing `hub` on Ubuntu with `Snap`

### CODE REVIEW

**Comment by mislav** [comment]
Thank you! Who manages the `hub` snap? How often does it get updated? What does `--classic` mean?

**Comment by felicianotech** [comment]
Hi,

I just have happened to come across this PR. Very cool to see this. To answer your questions:

1. I manage the `hub` snap.
2. The snap is typically updated within 24 hours of an official `hub` release. Once in awhile, it'll be within 48 hours.
3. `--classic` is what's called a "confinement type" for snaps. Someone asked me out that recently, [here was my response](https://github.com/felicianotech/hub-snap/issues/8).

Resources:

- hub Snap repository: https://github.com/felicianotech/hub-snap
- hub Snap Snap Store page: https://snapcraft.io/hub
- Current number of hub snap users, 760: https://www.feliciano.tech/blog/january-2019-snap-metrics/
- Official Snapcraft website: https://snapcraft.io/
- My explanation on why snaps are useful: https://www.feliciano.tech/blog/what-are-linux-snap-packages-why-use-them/

**Comment by mislav** [comment]
Hi @felicianotech thank you for explaining! 

Would it be possible to instead publish a snap from our Travis CI script in this repository on every tagged release? We already publish a GitHub Release, upload prebuilt binaries, and publish man pages on our website automatically.

**Comment by felicianotech** [comment]
This sounds possible. I have experience building and publishing a snap via CircleCI though Travis CI might be possible.

My concern would be with ongoing maintenance. Snapcraft is a developing software and sometimes changes need to be made to the snap file in order for it to continue to be built in the future. I would hate transfering over the `hub` snap namespace to this repo, and then 6 months from now it is dumped. There are 795 "weekly active devices" right now and I want to make sure the snap remains updated for those devices.

**Comment by mikob** [comment]
I think this should be approved because the apt package isn't even available on recent versions of ubuntu/mint AFAIK. So the README isn't useful without this PR.

**Comment by mislav** [comment]
Thank you all!

**Pull request merged**
