### PR TITLE
[WIP] commands: make fork() set remote.pushdefault

### PR DESCRIPTION
**Pull request by artagnon**
Hi,

Unfortunately, my patch doesn't work as expected, and I can't figure out why. Any clues?

Thanks.

### CODE REVIEW

**Comment by sambrightman** [comment]
I was about to submit a PR for exactly this feature. Why would you not want to do this? Automatic tasks that are annoying but trivial seems exactly what hub should do to me. Is there some sort of multi-remote setup where you would fork a GitHub repo and not want to push to your fork by default? It seems unlikely that you have write access to origin if you do this. It also seems unlikely that you can cause much damage by pushing to your fork.

**Comment by mislav** [comment]
@sambrightman The configuration setting looks innocent in theory, but in the long run the existence of the setting may cause headaches for some in a multi-git remote scenario when they don't understand that there was a `pushdefault` added for them. I'm trying to avoid hub doing anything potentially surprising.

Yes I agree that it makes the most sense that you would probably want to only push to your fork. I just don't find that it's too difficult to say `git push -u mislav HEAD` when publishing a branch to my fork. After that, for the same branch I can use `git pull/push` without arguments.

**Comment by sambrightman** [comment]
It still seems very unlikely to me that someone runs a complicated multi-remote setup, uses hub with it, and uses implicit push. If you run a complicated multi-remote setup, surely you use and explicit remote and this feature would not affect you. If you did accidentally run implicitly then pushing to your personal fork seems safer than pushing to random remote R.

How about setting this only if there is a single remote called `origin` setup, `remote.pushdefault` is unset, and all branches have `branch.<name>.remote` set to `origin` when `hub fork` is run? Something like that represents the canonical GitHub workflow.

**Comment by mislav** [comment]
Hub will not set any configuration options for you that you didn't ask for explicitly.

`hub fork` is just an alternative to forking a repo on GitHub web interface. It won't do anything other than that.

**Pull request closed without merging**
