### PR TITLE
Adding support for arm processors

### PR DESCRIPTION
**Pull request by IWriteThings**
Updating the cross compile script here to add support for arm processors.

### CODE REVIEW

**Comment by mislav** [comment]
This looks good! Have you verified that a non-ARM linux machine can cross-compile ARM binaries? I couldn't on OS X, and I'm wondering why.

**Comment by IWriteThings** [comment]
@mislav ,
I was able to  cross-compile the files in arm and arm64. Can you pull my latest commit and try it on your box? I am on Mac OSX 10.10.

Steps I took -

1. 
```
$ ./script/cross-compile comp
```

Do you have go > 1.5 ?
What errors are you getting?

**Comment by mislav** [comment]
Ah, your 2nd commit was key :) thanks!

**Comment by mislav** [comment]
The FreeBSD failure is known, unfortunately. We don't know what's causing it.

**Pull request merged**
