### PR TITLE
[pr] add ability to open Pull Request in the browser

### PR DESCRIPTION
**Pull request by ashemesh**
add the ability to open a PR page in browser (also copy & URL print to screen).
ability to open the forked PR by pass the `head` flag.
Screenshot 2019-05-18 at 22 41 31
in the example above `hub` is a fork of `github/hub`.

### CODE REVIEW

**Comment by ashemesh** [comment]
@mislav in the above scenario, if `origin` has PR with `feature` has the head, we query should `origin` and as a "fallback" check `upsteam` for a PR with `owner:feature` as head, do you agree?

**Comment by ashemesh** [comment]
@mislav is this cover the scenario you wrote above?
Screenshot 2019-05-25 at 22 04 57
I'm not so happy with the amount of `if \ else` in the function code, but I can't think how to support all the possible combinations, so maybe it is better not to support the `head` flag, what do you think?

**Comment by mislav** [comment]
@ashemesh I've cleaned up code & tests, added more tests, and added the `hub pr show <NUMBER>` functionality as per @whatsadebugger. Please review!

**Comment by ashemesh** [comment]
@mislav sorry only saw it now! thank you!

**Comment by mislav** [comment]
@ashemesh No worries; thank you for your contribution! 🎉

**Pull request merged**
