### PR TITLE
Add support for review requests in pull-request command

### PR DESCRIPTION
**Pull request by tomasv**
Fixes https://github.com/github/hub/issues/1358

I took the code from https://github.com/github/hub/pull/1422 and attempted to complete it. I hope @ConradIrwin does not mind. 👼 

I'm not sure what the cleanest way of overriding `Accept` for one request would be. Most options involve adding the `apiPayloadVersion` argument to a lot of function signatures and passing it through. Can this be improved?

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks @tomasv !

**Comment by hkdobrev** [comment]
Thanks for this! However, the title is a bit misleading as this adds support for only adding reviewers, not submitting reviews. I think it should be renamed similar to the issue it closes.

**Comment by mislav** [comment]
I've pushed some cleanups to this. Instead of setting a changed `Accept` header per single request, I've simply added the `Accept: application/vnd.github.black-cat-preview+json` value to all requests. This should have no adverse effect to the rest of the API functionality, and is only recognized by API endpoints that deal with reviewer functionality. Let me know what you think!

**Comment by mislav** [comment]
Hmm, I've just tested sending the 2 header values to GitHub API, but it doesn't recognize it:

```
> POST https://api.github.com/repos/mislav/playground/pulls/30/requested_reviewers
> Authorization: token [REDACTED]
> Accept: application/vnd.github.v3+json;charset=utf-8
> Accept: application/vnd.github.black-cat-preview+json
{"reviewers":["mislav"]}

< HTTP 415
{"message":"If you would like to help us test the Pull Request Reviews API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.","documentation_url":"https://developer.github.com/v3"}
```

It's possible that GitHub API doesn't deal well with multiple values of `Accept` header, even though it should in theory. I will follow up to see whether this is a bug in our API.

**Comment by tomasv** [comment]
@mislav is that an accurate representation of header values?

The final raw request header as I understand should look like this: `Accept: application/vnd.github.v3+json;charset=utf-8, application/vnd.github.black-cat-preview+json`. Relevant RFC: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by mislav** [comment]
@tomasv Specifying a header twice or specifying it once with two values separated by a comma should be equivalent. But, I'm just checking the implementation of this in the GitHub API, and it looks like we only take the 1st value of `Accept` and discard the rest. I'll check with the API team to see whether this was desired behavior or an oversight.

In the meantime, I'll try switching back to a custom `Accept` header just for this request.

**Comment by evnm** [comment]
Thank you for adding this! Will it be included in 2.3.0?

**Comment by mislav** [comment]
Yes, and I'll try to make a prerelease soon including this.

**Comment by AlexVKO** [comment]
hey, Is it currently working?

**Comment by mislav** [comment]
@AlexVKO You can try this functionality out if you build hub from the master branch. It's not yet released.

**Pull request merged**
