### PR TITLE
Update EDITMSG copy

### PR DESCRIPTION
**Pull request by justincampbell**
* Put "The" before description
* Add comma
* Reflow to 80 columns

### CODE REVIEW

**Comment by mislav** [comment]
Sorry, I don't see a value in this.

* The reflow doesn't affect users much. This text gets ignored anyway.
* The definite article before "description" doesn't sound like it's stricly necessary.
* A comma before "and" is not necessary unless it's an Oxford comma.

**Comment by justincampbell** [comment]
"and the rest is description" is not proper English. Happy to open a PR with just the "the" before description.

**Comment by mislav** [comment]
Sure, thanks. You should re-use this same PR.

**Comment by justincampbell** [comment]
Updated. I did reflow a tiny bit just so that the second line wasn't longer than the first.

**Comment by mislav** [comment]
The last bit you need to do is update the test suite so it reflects the change. Right now there is a test failure.

**Comment by justincampbell** [comment]
Weird, script/test passes locally for me. Can you re-run?

-Justin

github.com/justincampbell
twitter.com/justincampbell

On July 8, 2015 at 12:14:42 PM, Mislav Marohnić (notifications@github.com) wrote:

The last bit you need to do is update the test suite so it reflects the change. Right now there is a test failure.

**Comment by mislav** [comment]
Does this pass for you? `bundle exec cucumber features/pull_request.feature:115`

**Comment by justincampbell** [comment]
Ah I see, updated!

**Comment by mislav** [comment]
Thanks for being patient.

**Pull request merged**
