### PR TITLE
Add chocolatey and powershell instructions.

### PR DESCRIPTION
**Pull request by dougludlow**

### CODE REVIEW

**Comment by mislav** [comment]
Hi thanks for your contibution! The docs look really solid. But I have two issues with the content. First of all, Chocolatey is nice and all, but our releases there are really out of date and I don't recommend installing them because of known bugs. I don't know how to upgrade those packages. So before we can add this documentation, we need to figure that out. See #1288

Second, those Powershell instructions look really complicated, with separate steps if your config file already exists or not. Is it possible to make a single command that works regardless of whether a config file is already there?

**Comment by dougludlow** [comment]
Hi @mislav, sure I'll take a look at #1288. I've been using the chocolately version just fine for a while, but I understand.

Regarding a single command, I played around with one. I'm no powershell expert, but in powershell it's a very complicated/long one liner, something like this:

``` sh
Write-Output "`nSet-Alias git hub" | %{If (Test-Path $PROFILE) { Out-File -Encoding utf8 -Append -InputObject $_ -Filepath $PROFILE } Else { New-Item -Force -Path $PROFILE -Value $_ -Type file }}
```

If you're fine with that I can put it in instead. I thought it might be simpler to break it up into multiple commands.

**Comment by mislav** [comment]
You're right, it does look simpler if we break it up. Let's go for the
shortest possible instructions. We don't want to have people copy/pasting
huge chunks of code in their terminal that they don't understand.

**Comment by dougludlow** [comment]
@mislav I can't remember where we landed on this. Was there anything I needed to change here?

**Comment by mislav** [comment]
Thanks for the patience!

**Pull request merged**
