### PR TITLE
Use a formatter to choose the display of issues like `git log --format`.

### PR DESCRIPTION
**Pull request by pcorpet**
This will be used to choose the formatting of issues (in `hub issue`) or pull requests (in `hub pr`).

### CODE REVIEW

**Comment by mislav** [comment]
Hi thanks for this! Tests look good, although I would prefer individual test cases instead of a giant loop.

The implementation looks quite complex and it will take me a bit to review it. For now, don't worry about colorization modifiers; maybe we could [yank some features from here](https://github.com/mislav/go-utils/blob/81c68ebbe32bbfdabad160a35ee6feb244d53372/cli/colored_writer.go).

**Comment by pcorpet** [comment]
I've split the test in smaller (and logical) chunks and added missing colors. Thanks for the heads up that you'll need some time to review.

**Comment by pcorpet** [comment]
A friendly ping.

**Comment by pcorpet** [comment]
@mislav any chance I can get your attention?

**Comment by mislav** [comment]
Hey, sorry for no 👀 . I haven't been working on hub for a while, but I am trying to push for a release soon-ish. This would be great to get in. Could you demonstrate how to usage code for this would look like within hub?

**Comment by pcorpet** [comment]
For instance in the listIssues command, this would look like:

```Go
cmdIssue.Flag.StringVarP(&flagIssueFormat, "format", "f", "%>(8)%hash  %title", "FORMAT")
defaultIssueFormat = ""

ui.Print(ui.Expand(flagIssueFormat, map[string]string{
  "hash": fmt.Sprintf("#%d", issue.Number), 
  "title": issue.Title,
  "number": fmt.Sprintf("%d", issue.Number),
  "body": issue.Body,
  "user": issue.User.Login,
  "assignee": issue.Assignee.Login,
  ...
}))
```

By default it keeps the same display you had before (well almost, we would need to be a bit smarter about colors), but it's now customizable and users can run it with a --format flag
```shell
hub issue --format "%>(8)%hash  %<(15)%assignee  %title%n%body"
```

Of course we can make shorter varnames as well as compute better vars.

**Comment by mislav** [comment]
@pcorpet That looks great. If I merged in https://github.com/github/hub/pull/1099 to master, could you merge master in here and hook up `hub issue` with the `--format` flag like you explained? Then I would merge this PR.

**Comment by pcorpet** [comment]
Of couse, just waiting on you to merge #1099 to master then.

**Comment by pcorpet** [comment]
Done.

**Comment by mislav** [comment]
@pcorpet Oh. I wanted to first merge #1099 to master before you made your changes. Otherwise it's going to conflict.

**Comment by pcorpet** [comment]
No problem (note that I based my work on #1099 already). Please do the merge and ping me when ready.

**Comment by mislav** [comment]
> note that I based my work on #1099 already

Oh! I never realized. Ok, then that makes sense. The ball is in my court now.

**Pull request merged**
