### PR TITLE
Don't corrupt the PATH if longer than 1024 characters on Windows

### PR DESCRIPTION
**Pull request by jamesqo**
setx automatically truncates the PATH to 1024 characters if it is longer than that, which is no good. It also mucks up the local user's PATH with the machine-wide PATH.

This PR fixes that by using PowerShell to manually alter the PATH.

### CODE REVIEW

**Comment by mislav** [comment]
Thanks for the fix! Unfortunately, this new code is quote hard to interpret as a human. Is it possible to try to clean up the code, or at least document it? I'm reluctant to pull in code that I don't know what it does.

**Comment by jamesqo** [comment]
Sure, no problem. Thanks for responding :smile:

**Comment by mislav** [comment]
Thanks for adding docs! Have you tested this manually?

**Comment by jamesqo** [comment]
Just tested, it seems to be working after I made a few changes:

image

**Comment by mislav** [comment]
Thanks!

**Pull request merged**
