### PR TITLE
All supported shells added to hub.zsh_completion

### PR DESCRIPTION
**Pull request by hasit**
Added all supported shells (bash zsh sh ksh csh tcsh fish) to keep it consistent with commands/alias.go

### CODE REVIEW

**Comment by mislav** [comment]
Sorry, we can't advertise support for `sh`, `tcsh`, `fish` before we tested them! For instance, we don't yet have fish completion. Also, I feel current completion script for bash wouldn't run in `sh` because it wouldn't have all the bash features needed. I don't think many people are using `sh` for their login shell anyway.

I will work on merging #788 instead.

**Comment by hasit** [comment]
@mislav This PR is for aliasing hub as git. commands/alias.go supports alias script for all those shells.

**Comment by mislav** [comment]
Ah, correct; thanks for clarifying.

**Comment by mislav** [comment]
I have decided that this is not necessary; i.e. correct tab completion for `hub alias` is not important since `hub alias` is a semi-internal command that serves just for hub configuration and users will not interact with it daily. Plus, I am not ready to pull in the additional commits in this PR that were adopted from another PR.

**Pull request closed without merging**
