### PR TITLE
Enhance `hub api` to recognise an empty array field

### PR DESCRIPTION
**Pull request by simon-engledew**
Hey, thanks for hub!

I made this tiny tweak to allow me to bypass `required_contexts` when doing staging deployments. The endpoint requires an empty array:

  image

But hub currently sends the JSON string `"[]"`. This change will send the empty array instead.

Changing the behaviour might not be desirable in the main repository! 😄 If nothing else, hopefully this has a bunch of useful keywords for anyone else with the same problem.

Let me know if you want me to do any additional work on it or feel free to close it if it's too niche.

Cheers,
~ Si

### CODE REVIEW

**Comment by simon-engledew** [comment]
Sure - that sounds like a more useful addition! 😄 

I was a little bit worried about overloading the `--field` argument with behaviour that could break existing (valid) usage.

Rather than add a special case that checks for a valid array, I've added a new argument: `--json-field`. 

This will validate that the JSON is correct, but otherwise pass it unaltered directly to ENDPOINT.

I originally used `json.Valid`, but you can't get the error message returned from the scanner. 😭 Unmarshalling the JSON into an empty interface gives you a helpful error message at the expense of some additional overhead:

image

**Comment by simon-engledew** [comment]
Using --field

image

Using --json-field

image

**Comment by mislav** [comment]
> Rather than add a special case that checks for a valid array, I've added a new argument: `--json-field`.

Thanks for doing that! But I would like us to backtrack a little bit.

The primary point of the `hub api` command was to handle JSON encoding & decoding for environments that don't have access to JSON facilities (e.g. bash scripts). With the new `--json-field` flag, it looks like people will be required to construct valid JSON by hand again, which defeats the point of `hub api`.

Instead, what do you think about the syntax proposed in the GitHub CLI repo? https://github.com/cli/cli/issues/1484

**Comment by simon-engledew** [comment]
> > Rather than add a special case that checks for a valid array, I've added a new argument: `--json-field`.
> 
> Thanks for doing that! But I would like us to backtrack a little bit.
> 
> The primary point of the `hub api` command was to handle JSON encoding & decoding for environments that don't have access to JSON facilities (e.g. bash scripts). With the new `--json-field` flag, it looks like people will be required to construct valid JSON by hand again, which defeats the point of `hub api`.
> 
> Instead, what do you think about the syntax proposed in the GitHub CLI repo? [cli/cli#1484](https://github.com/cli/cli/issues/1484)

Oh, that looks cool – great idea! 👍I think that is a way better solution. 😸

It looks like the syntax for Rails array parameters, so there is prior art - and that seems to be holding up pretty well after over a decade of use. 😄

I also really like the nested object syntax, although I can see that being more divisive. 🤔 I guess the alternative is adding more subcommands for APIs that require nested inputs and keeping `api` lean? Tough call!

Thanks for taking the time to think about this issue! I'll close this PR and keep an eye on that issue instead. 👁️

**Pull request closed without merging**
