### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by e-beach** [comment]
@dvrkps You might want to check why tests failed. Also, I think you should really say `1.9` instead of `1.x`, variable versions leads to unstable builds.

**Comment by dvrkps** [comment]
@e-beach i think ruby tests fails for some reason.

**Comment by mislav** [comment]
Why are we updating Go version? This project is tailored for Go 1.8.x right now. We do, of course, want to support the latest Go version as well, but first and foremost we want to ensure that we maintain compatibility with Go 1.8 until we're ready to deliberatly drop that compatibility. Specifying `1.x` in Travis configuration means that the test suite wouldn't be run against 1.8 anymore.

Ruby tests sometimes have intermittent failures. I've restarted the build in hopes the failure would clear up.

**Comment by dvrkps** [comment]
@mislav @e-beach I can add both 1.8.x and 1.9.x instead only 1.x for maintain compatibility ?

**Comment by e-beach** [comment]
@dvrkps I think that is what Mislav is saying.

**Comment by dvrkps** [comment]
I close this PR and add new with both go versions.

**Comment by mislav** [comment]
You didn't have to close this PR: you could have simply pushed new commits to your branch. But thank you!

**Comment by dvrkps** [comment]
I know, but i delete fork repo before.

**Pull request closed without merging**
