### PR TITLE
Code of Conduct

### PR DESCRIPTION
**Pull request by bkeepers**
We are intending to adopt the soon-to-be-announced [Open Code of Conduct](http://todogroup.org/opencodeofconduct) for all @github projects. This adds it to the contributing guidelines. Let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by parkr** [comment]
Really great, @bkeepers! :+1:

**Comment by jingweno** [comment]
:+1: I saw the same code of conduct is applying to Go this morning at the keynote of GopherCon, wondering if there's any correlation of that :)

**Comment by bkeepers** [comment]
> I saw the same code of conduct is applying to Go this morning at the keynote of GopherCon, wondering if there's any correlation of that :)

Nice, is there a link to that? This is an effort we're coordinating with several other companies, but I didn't realize Go was adopting it too.

**Comment by jingweno** [comment]
> Nice, is there a link to that? 

The Go team published this [blog post](http://blog.golang.org/open-source) immediately after the keynote (scroll down to the section "Code of Conduct"). I'm sure the recordings and slides of @rsc's keynote will be available soon.

**Comment by rsc** [comment]
The Go team is still deciding details, but seeing this version is useful input to that process. Thanks. /cc @adg

**Comment by parkr** [comment]
:clap:

**Pull request merged**
