### PR TITLE
Check for empty git config

### LINKED ISSUE #858: Crash report - runtime error: index out of range
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
github.com/github/hub/git.gitGetConfig(0xc2080818b8, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/git/git.go:180 +0x3d6
github.com/github/hub/git.Config(0x47f530, 0x8, 0x0, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/git/git.go:162 +0xc6
github.com/github/hub/github.knownGitHubHosts(0xc20801f220, 0x2, 0x2)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/github/hosts.go:31 +0x231
github.com/github/hub/github.NewProjectFromURL(0xc2080113b0, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/github/project.go:105 +0x4b
github.com/github/hub/github.ParseURL(0x7fff5fbff302, 0xe, 0x1, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/github/url.go:28 +0x89
github.com/github/hub/commands.transformMergeArgs(0xc2080581b0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/merge.go:44 +0xca
github.com/github/hub/commands.merge(0x688120, 0xc2080581b0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/merge.go:32 +0x40
github.com/github/hub/commands.(*Command).Call(0x688120, 0xc2080581b0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/commands.go:46 +0x189
github.com/github/hub/commands.(*Runner).Call(0xc208029120, 0x688120, 0xc2080581b0, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/runner.go:89 +0x54
github.com/github/hub/commands.(*Runner).Execute(0xc208029120, 0x0, 0x0, 0x0)
	/var/folders/w8/dp0lmdjs2vs51lsxbrf4s49h0000gn/T/go/src/github.com/github/hub/commands/runner.go:81 +0x215
main.main()
	/private/tmp/hub-xGkPdT/hub-2.2.0/main.go:12 +0x40

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

### PR DESCRIPTION
**Pull request by jingweno**
This fixes #858

### CODE REVIEW

**Comment by jingweno** [comment]
@mislav Hmm...I tried to accept the CLA, but I'm getting:

screen shot 2015-04-06 at 2 14 26 pm

Could you check? The URL with the error page is https://cla.github.com/401025/accept/jingweno

**Comment by bkeepers** [comment]
Hi @jingweno, sorry about the issue. I'm working on it right now.

**Comment by bkeepers** [comment]
@jingweno can you try again, the URL should be: https://cla.github.com/github/hub/accept/jingweno

Thanks!

**Comment by jingweno** [comment]
@bkeepers It works. You're fast :+1:

**Comment by mislav** [comment]
Looks good thanks! :+1:

**Pull request merged**
