### PR TITLE
Strip co-author from PR descriptions

### LINKED ISSUE #2311: hub pull-request should trim or string replace `Co-authored-by` and `Signed-off-by` footer fields from PR description
Currently, if you have created one or more commits with [multiple authors](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) and then use `hub pull-request ...` to submit a PR for the changes, the Co-author-by: fields are included in the description, but do not render cleanly in Markdown due to the e-mail addresses being automatically replaced with mailto hrefs. 

e.g., Co-authored-by: NAME <email@example.com>

It is probably preferable not to include e-mail addresses in PR descriptions anyway, so it seems like it'd be best to just exclude them from the extracted PR description? This also applies to `Signed-off-by:` declarations.

### PR DESCRIPTION
**Pull request by sinisterstuf**
The Signed-off-by string already gets stripped, so I extended the regular expression to also match Co-authored-by.

Resolves #2311

### CODE REVIEW

**Comment by sinisterstuf** [comment]
Tests aren't running correctly on my laptop, so I'm using the pull request triggered Travis builds as a playground, sorry about that. I'll squash once it's working.

**Comment by sinisterstuf** [comment]
Cool, so now the existing taste cases don't break but I haven't added any new ones... yet.

**Comment by sinisterstuf** [comment]
So instead of adding a new test case, I added the new "Co-auhored-by" line to the existing test input and the expected result is still the same; that none of them will be present in the final PR description. Hopefully that's fine.

**Comment by mislav** [comment]
Thank you!

**Pull request merged**
